[package]
name = "turbo-crates"
version = "0.1.0"
edition = "2021"
authors = ["Arunas Iva"]
description = "A set of useful crates (WIP)"
repository = "https://github.com/ariva/turbo-crates.git"
license = "MIT OR Apache-2.0"

[workspace]
members = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
